version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      # Mount the project directory from the host into the container
      - ..:/workspaces/RosterConnect:cached
    env_file:
      - .devcontainer/.env.development
    depends_on:
      - dev-db

  dev-db:
    image: postgres:alpine3.21
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # Persist the database data to a volume
      - dev-db-data:/var/lib/postgresql/data
    ports:
      # Expose the database port (optional, useful for external tools)
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  dev-db-data: